name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (optional, for npm builds)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies (optional)
      run: npm install

    - name: Inject GitHub Secret into login.js
      run: |
        echo "const adminPassword = '${{ secrets.ADMIN_PASSWORD }}';" > login.js

    - name: Build project (optional, if using a build tool)
      run: npm run build  # Or any other build command you need

    - name: Deploy to GitHub Pages
      run: |
        git add .
        git commit -m "Deploy"
        git push

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Target branch to deploy
        folder: build  # Folder to deploy (adjust according to your setup)
